{% set version = "2.17.13" %}

package:
  name: axel
  version: {{ version }}

source:
  url: https://github.com/axel-download-accelerator/axel/releases/download/v{{ version }}/axel-{{ version }}.tar.gz
  sha256: 604ce7fbdb37500c462295d6c03fa59eb4dffb780fdf2fc3c41ffa75c8f6ec38

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
  host:
    - gettext
    - openssl

test:
  commands:
    - axel --version
    - axel --help
    - axel https://github.com/ -o download-test.html
    - rm download-test.html

about:
  home: https://github.com/axel-download-accelerator/axel
  license: GPL-2.0-or-later WITH openvpn-openssl-exception
  license_file: COPYING
  summary: Lightweight CLI download accelerator

extra:
  recipe-maintainers:
    - jdblischak
